<?php
include_once 'templates/header.template.phtml';
?>
<link rel="stylesheet" href="carrito.css">
<div class="card">
            <div class="row">
                <div class="col-md-8 cart">
                    <div class="title">
                        <div class="row">
                            <div class="col"><h4><b>Carrito</b></h4></div>
                            <div class="col align-self-center text-right text-muted">3 items</div>
                        </div>
                    </div>    
                    <div class="row border-top border-bottom">
                        <div class="row main align-items-center">
                            <div class="col-2"><img class="img-fluid" src=""></div>
                            <div class="col">
                                <div class="row text-muted">Lavandina</div>
                                <div class="row">Lavandina ayudaza</div>
                            </div>
                            <div class="col">
                                <a href="#">-</a><a href="#" class="border">1</a><a href="#">+</a>
                            </div>
                            <div class="col">$200 <span class="close"></span></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="row main align-items-center">
                        <div class="col-2"><img class="img-fluid" src=""></div>
                            <div class="col">
                                <div class="row text-muted">Lavandina</div>
                                <div class="row">Lavandina ayudaza</div>
                            </div>
                            <div class="col">
                                <a href="#">-</a><a href="#" class="border">1</a><a href="#">+</a>
                            </div>
                            <div class="col">$200 <span class="close"></span></div>
                        </div>
                    </div>
                    <div class="row border-top border-bottom">
                        <div class="row main align-items-center">
                        <div class="col-2"><img class="img-fluid" src=""></div>
                            <div class="col">
                                <div class="row text-muted">Lavandina</div>
                                <div class="row">Lavandina ayudaza</div>
                            </div>
                            <div class="col">
                                <a href="#">-</a><a href="#" class="border">1</a><a href="#">+</a>
                            </div>
                            <div class="col">$200 <span class="close"></span></div>
                        </div>
                    </div>
                    <div class="back-to-shop"><a href="#">&leftarrow;</a><span class="text-muted">volver</span></div>
                </div>
                <div class="col-md-4 summary">
                    <div><h5><b>Resumen</b></h5></div>
                    <hr>
                    <div class="row">
                        <div class="col" style="padding-left:0;">ITEMS 3</div>
                        <div class="col text-right">$ 600</div>
                    </div>
                    <form>
                        <p>ENVIO</p>
                        <select><option class="text-muted">Envio gratis</option></select>
                        <p>CODIGO PROMOCIONAL</p>
                        <input id="code" placeholder="Enter your code">
                    </form>
                    <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                        <div class="col">PRECIO TOTAL</div>
                        <div class="col text-right">$ 600</div>
                    </div>
                    <button class="btn">IR AL PAGO</button>
                </div>
            </div>
            
        </div>

<?php include_once 'templates/footer.template.phtml';?>