<?php
include_once 'templates/header.template.phtml';
?>
<h1 class="mt-5 align-center">Carrito</h1>
<ul class="list-group mt-5">
    <?php for($i = 0; $i<count($productos); $i++) { 
        $producto = $productos[$i];
        ?>
        <li class="list-group-item">
            <?php echo $producto->nombre; ?>
            $ <?php echo $producto->precio; ?>
            Cantidad: <?php echo $carrito[$i]->cantidad; ?>

            <a href="delete/<?php echo $producto->id ?>" class="btn btn-primary">Quitar del carrito</a>
        </li>
    <?php
    } ?>
</ul>

<?php include_once 'templates/footer.template.phtml'; ?>