<?php
include_once 'templates/header.template.phtml';
?>

<div class="row g-3 align-items-center mt-5 mx-auto w-25">
<div class="col-md-4">
    </div>
    <div class="col-md-4">
        <form method="POST" action="update/producto/<?php echo $producto[0]->id?>">
            <div class="form-group">
            <label>Nombre</label>
            <input type="text" class="form-control" name="nombre" aria-describedby="emailHelp" placeholder="<?php echo $producto[0]->nombre?>">
        </div>
        <div class="form-group">
            <label>Descripcion</label>
            <input type="text" class="form-control" name="descripcion" aria-describedby="emailHelp" placeholder="<?php echo $producto[0]->descripcion?>">
        </div>
        <div class="form-group">
            <label>Precio</label>
            <input type="number" class="form-control" name="precio" aria-describedby="emailHelp" placeholder=" $ <?php echo $producto[0]->precio?>">
        </div>
        <div class="form-group">
            <label>Imagen</label>
            <input type="text" class="form-control" name="imagen" aria-describedby="emailHelp" placeholder=" ruta <?php echo $producto[0]->imagen?>">
        </div>
        <div class="form-group">
            <label>ID categoria</label>
            <input type="number" class="form-control" name="id_categoria" aria-describedby="emailHelp" placeholder="<?php echo $producto[0]->id_categoria?>">
        </div>
        
        <button type="submit" class="btn btn-primary mt-5">Guardar</button>
    </form>
    </div>
    <div class="col-md-4">
    </div>
</div>
<?php
include_once 'templates/footer.template.phtml';
?>