<!DOCTYPE html>
<html lang="en">
<head>
    <base href=""> //url base de la pagina
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CLean</title>
    <link rel="stylesheet" href="css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <header>
        <h1>CLean</h1>
        <nav>
            <a href="inicio">Inicio</a>
            <a href="productos">Productos</a>
            <a href="carrito">Carrito</a>
            <a href="login">Log in</a>
        </nav>
    </header>
    <section>
        <span>LPM</span>
    </section>