<!doctype html>
<html lang="en" data-bs-theme="auto">
  <body>

<?php include_once './templates/header.template.phtml'
?>
<main>
  <div class="container">
  <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <h1>.</h1>
      </div>
      <div class="col-md-4">
      </div>
    </div>
    <div class="row" style="background-color:#000030">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <img src="css/img/logo_clean.png" alt="logo">
      </div>
      <div class="col-md-3">
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <h1>Todo para limpiar tu hogar</h1>
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </div>  
  <div class="demo-categorias">
    <?php 
    foreach($categorias as $categoria){
    ?>
        <div class="col-md-3">
          <div>
            <img src="<?php echo $categoria->img; ?>"  class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></img>
            <h2 class="fw-normal"><?php echo $categoria->nombre; ?></h2>
            <p><?php echo $categoria->descripcion; ?></p>

          </div>
        </div>
    <?php }?>

  

    

  </div><!-- /.container -->


  <!-- FOOTER -->
  <?php
  include_once './templates/footer.template.phtml'
  ?>
</main>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>