
<?php
include_once 'templates/header.template.phtml';
?>

<div class="row g-3 align-items-center mt-5 mx-auto w-25">
  <div class="col-md-4">
      </div>
  <form method="POST" action="auth">
  <div class="form-group">
    <label for="exampleInputEmail1">Nombre de usuario</label>
    <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder=" Ingrese su nombre de usuario">
  </div>
  <div class="form-group mb-3">
    <label for="exampleInputPassword1">Contraseña</label>
    <input type="password" class="form-control" name="password" placeholder="Password">
  </div>
<button type="submit" class="btn btn-primary">Ingresar</button>
</form>
</div>
<?php
include_once 'templates/footer.template.phtml';
?>