<?php
include_once 'templates/header.template.phtml';

?>
<div class="row mt-5 mx-auto">
    <div class="col-md-4">
    </div>
    <div class="col-sm-3 ">
        <div class="card mt-5">
            <div class="card-body shadow">
                <img src="<?php echo $producto[0]->imagen ?>" alt="" class="figure-img img-fluid rounded mx-auto">
                <h5 class="card-title"><?php echo $producto[0]->nombre; ?></h5>
                <h5 class="card-title"> $ <?php echo $producto[0]->precio; ?></h5>
                <p><?php echo $producto[0]->descripcion ?></p>
                <a href="add/<?php echo $producto[0]->id_categoria . "/" . $producto[0]->id ?>" class="btn btn-primary">Agregar al carrito</a>
                <?php
                if($isAdmin){?>
                <a href="<?php echo $producto[0]->id . "/editar" ?>" class="btn btn-primary">Editar</a>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<?php
include_once 'templates/footer.template.phtml';
?>