<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>CLean Limpieza</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/carousel/">

    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">


    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>

<?php include_once './templates/header.template.phtml'
?>
<main>
  <div class="container">
  <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <h1>.</h1>
      </div>
      <div class="col-md-4">
      </div>
    </div>
    <div class="row" style="background-color:#000030">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <img src="css/logo_clean.png" alt="logo">
      </div>
      <div class="col-md-3">
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <h1>Todo para limpiar tu hogar</h1>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>  
      <div class="container marketing">

        <div class="row">
          <div class="col-lg-3">
            <img src="css/img/bano.jpg" alt="cat_bano" class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></img>
            <h2 class="fw-normal">Baño</h2>
            <p>Todo lo que necesitas para dejar tu baño brillante.</p>
            <p><a class="btn btn-secondary" href="bano">Ver productos</a></p>
          </div>
          <div class="col-lg-3">
            <img src="css/img/cocina.jpg" alt="cat_cocina" class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
            <h2 class="fw-normal">Cocina</h2>
            <p>Productos para hacer brillar tu cocina.</p>
            <p><a class="btn btn-secondary" href="cocina">Ver productos</a></p>
          </div>
          <div class="col-lg-3">
            <img src="css/img/casa.jpg" alt="cat_bano" class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></img>
            <h2 class="fw-normal">Casa</h2>
            <p>Todo para tu casa.</p>
            <p><a class="btn btn-secondary" href="casa">Ver productos</a></p>
          </div>
          <div class="col-lg-3">
            <img src="css/img/jardin.jpg" alt="cat_bano" class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></img>
            <h2 class="fw-normal">Jardin</h2>
            <p>Deja tu jardin en orden.</p>
            <p><a class="btn btn-secondary" href="">Ver productos</a></p>
          </div>
        </div>


  

    

  </div><!-- /.container -->


  <!-- FOOTER -->
  <?php
  include_once './templates/footer.template.phtml'
  ?>
</main>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>